Repository TrainingDiary/training-diary-backend, pull requests merged in 2024-07, with the labels that each got.

#29 Redis로 토큰 발행 및 검증 최적화
  build.gradle
  src/main/java/com/project/trainingdiary/config/RedisConfig.java
  src/main/java/com/project/trainingdiary/provider/CookieProvider.java
  src/main/java/com/project/trainingdiary/provider/TokenProvider.java
  src/main/java/com/project/trainingdiary/repository/RedisTokenRepository.java
  src/main/java/com/project/trainingdiary/security/JwtAuthenticationFilter.java
  src/main/java/com/project/trainingdiary/service/UserService.java
  src/test/java/com/project/trainingdiary/service/UserServiceTest.java
Labels: enhancement, feature

#32 트레이너의 일정 수락
  src/main/java/com/project/trainingdiary/controller/ScheduleController.java
  src/main/java/com/project/trainingdiary/dto/request/AcceptScheduleRequestDto.java
  src/main/java/com/project/trainingdiary/entity/PtContractEntity.java
  src/main/java/com/project/trainingdiary/entity/ScheduleEntity.java
  src/main/java/com/project/trainingdiary/exception/impl/ScheduleStatusNotReserveApplied.java
  src/main/java/com/project/trainingdiary/exception/impl/UsedSessionExceededTotalSession.java
  src/main/java/com/project/trainingdiary/security/SecurityConfig.java
  src/main/java/com/project/trainingdiary/service/ScheduleService.java
  src/test/java/com/project/trainingdiary/service/ScheduleServiceTest.java
Labels: feature

#38 트레이너의 일정 거절
  src/main/java/com/project/trainingdiary/controller/ScheduleController.java
  src/main/java/com/project/trainingdiary/dto/request/RejectScheduleRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/RejectScheduleResponseDto.java
  src/main/java/com/project/trainingdiary/entity/ScheduleEntity.java
  src/main/java/com/project/trainingdiary/service/ScheduleService.java
  src/test/java/com/project/trainingdiary/service/ScheduleServiceTest.java
Labels: feature

#41 운동 일지 이미지 업로드
  build.gradle
  src/main/java/com/project/trainingdiary/config/AwsS3Config.java
  src/main/java/com/project/trainingdiary/controller/WorkoutSessionController.java
  src/main/java/com/project/trainingdiary/controller/WorkoutTypeController.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutImageRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/WorkoutImageResponseDto.java
  src/main/java/com/project/trainingdiary/dto/response/WorkoutSessionResponseDto.java
  src/main/java/com/project/trainingdiary/entity/WorkoutMediaEntity.java
  src/main/java/com/project/trainingdiary/entity/WorkoutSessionEntity.java
  src/main/java/com/project/trainingdiary/exception/impl/InvalidFileTypeException.java
  src/main/java/com/project/trainingdiary/exception/impl/MediaCountExceededException.java
  src/main/java/com/project/trainingdiary/repository/WorkoutSessionRepository.java
  src/main/java/com/project/trainingdiary/security/SecurityConfig.java
  src/main/java/com/project/trainingdiary/service/WorkoutSessionService.java
  src/main/resources/application-sample.yml
  src/main/resources/application-test.yml
  src/test/java/com/project/trainingdiary/service/WorkoutSessionServiceTest.java
Labels: feature

#37 유저 정보 조회 기능, Validation 검증 Handler 기능 구현
  src/main/java/com/project/trainingdiary/controller/SampleController.java
  src/main/java/com/project/trainingdiary/controller/UserController.java
  src/main/java/com/project/trainingdiary/dto/response/CommonResponse.java
  src/main/java/com/project/trainingdiary/dto/response/MemberInfoResponseDto.java
  src/main/java/com/project/trainingdiary/entity/BlacklistedTokenEntity.java
  src/main/java/com/project/trainingdiary/handler/GlobalExceptionHandler.java
  src/main/java/com/project/trainingdiary/handler/ValidationHandler.java
  src/main/java/com/project/trainingdiary/model/SuccessMessage.java
  src/main/java/com/project/trainingdiary/security/SecurityConfig.java
  src/main/java/com/project/trainingdiary/service/UserService.java
  src/main/resources/application-sample.yml
  src/test/java/com/project/trainingdiary/service/UserServiceTest.java
Labels: feature

#45 트레이너의 일정 등록
  src/main/java/com/project/trainingdiary/controller/ScheduleController.java
  src/main/java/com/project/trainingdiary/dto/request/RegisterScheduleRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/RegisterScheduleResponseDto.java
  src/main/java/com/project/trainingdiary/entity/PtContractEntity.java
  src/main/java/com/project/trainingdiary/exception/impl/PtContractNotEnoughSession.java
  src/main/java/com/project/trainingdiary/service/ScheduleService.java
  src/test/java/com/project/trainingdiary/service/ScheduleServiceTest.java
Labels: feature

#47 PT 계약 목록 조회 수정
  src/main/java/com/project/trainingdiary/controller/PtContractController.java
  src/main/java/com/project/trainingdiary/dto/response/PtContractResponseDto.java
  src/main/java/com/project/trainingdiary/entity/PtContractEntity.java
  src/main/java/com/project/trainingdiary/model/PtContractSort.java
  src/main/java/com/project/trainingdiary/repository/ptContract/PtContractRepository.java
  src/main/java/com/project/trainingdiary/repository/ptContract/PtContractRepositoryCustom.java
  src/main/java/com/project/trainingdiary/repository/ptContract/PtContractRepositoryImpl.java
  src/main/java/com/project/trainingdiary/service/PtContractService.java
  src/main/java/com/project/trainingdiary/service/ScheduleService.java
  src/main/java/com/project/trainingdiary/service/WorkoutSessionService.java
  src/test/java/com/project/trainingdiary/service/PtContractServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleServiceTest.java
  src/test/java/com/project/trainingdiary/service/WorkoutSessionServiceTest.java
Labels: feature

#50 운동 일지 동영상 업로드
  src/main/java/com/project/trainingdiary/controller/WorkoutSessionController.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutVideoRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/WorkoutVideoResponseDto.java
  src/main/java/com/project/trainingdiary/service/WorkoutSessionService.java
  src/main/resources/application-sample.yml
  src/main/resources/application-test.yml
  src/test/java/com/project/trainingdiary/service/WorkoutSessionServiceTest.java
  src/test/resources/application-test.yml
Labels: feature

#53 Github Action과 EC2를 사용한 배포 CI/CD 구축
  .github/workflows/deploy.yml
  appspec.yml
  build.gradle
  scripts/startup.sh
  src/main/java/com/project/trainingdiary/config/SwaggerConfig.java
  src/main/resources/application-sample.yml
Labels: enhancement

#51 트레이너와 트레이니의 일정 취소
  src/main/java/com/project/trainingdiary/controller/ScheduleController.java
  src/main/java/com/project/trainingdiary/dto/request/CancelScheduleByTraineeRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/CancelScheduleByTrainerRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/CancelScheduleByTraineeResponseDto.java
  src/main/java/com/project/trainingdiary/dto/response/CancelScheduleByTrainerResponseDto.java
  src/main/java/com/project/trainingdiary/entity/ScheduleEntity.java
  src/main/java/com/project/trainingdiary/exception/impl/ScheduleStartWithin1Day.java
  src/main/java/com/project/trainingdiary/exception/impl/ScheduleStatusNotReserveAppliedOrReserved.java
  src/main/java/com/project/trainingdiary/service/ScheduleOpenCloseService.java
  src/main/java/com/project/trainingdiary/service/ScheduleService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTraineeService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTrainerService.java
  src/test/java/com/project/trainingdiary/service/ScheduleOpenCloseServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTraineeServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTrainerServiceTest.java
Labels: feature

#59 PT 계약 관련 API 수정
  src/main/java/com/project/trainingdiary/controller/PtContractController.java
  src/main/java/com/project/trainingdiary/dto/request/CreatePtContractRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/TerminatePtContractRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/CreatePtContractResponseDto.java
  src/main/java/com/project/trainingdiary/exception/impl/PtContractAlreadyExistException.java
  src/main/java/com/project/trainingdiary/service/PtContractService.java
  src/main/resources/application-sample.yml
  src/test/java/com/project/trainingdiary/service/PtContractServiceTest.java
Labels: feature

#61 운동 관련 코드 수정
  src/main/java/com/project/trainingdiary/controller/WorkoutSessionController.java
  src/main/java/com/project/trainingdiary/controller/WorkoutTypeController.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutImageRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutSessionCreateRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutTypeCreateRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutTypeUpdateRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutVideoRequestDto.java
  src/main/java/com/project/trainingdiary/entity/WorkoutTypeEntity.java
  src/main/java/com/project/trainingdiary/exception/impl/InvalidFileTypeException.java
  src/main/java/com/project/trainingdiary/exception/impl/InvalidUserRoleTypeException.java
  src/main/java/com/project/trainingdiary/exception/impl/MediaCountExceededException.java
  src/main/java/com/project/trainingdiary/exception/impl/TrainerIdNotFoundException.java
  src/main/java/com/project/trainingdiary/exception/impl/WorkoutSessionAccessDeniedException.java
  src/main/java/com/project/trainingdiary/repository/WorkoutSessionRepository.java
  src/main/java/com/project/trainingdiary/repository/WorkoutTypeRepository.java
  src/main/java/com/project/trainingdiary/security/SecurityConfig.java
  src/main/java/com/project/trainingdiary/service/WorkoutSessionService.java
  src/main/java/com/project/trainingdiary/service/WorkoutTypeService.java
  src/test/java/com/project/trainingdiary/service/WorkoutSessionServiceTest.java
  src/test/java/com/project/trainingdiary/service/WorkoutTypeServiceTest.java
Labels: refactoring

#56 트레이니와 트레이너의 일정 조회 분리
  src/main/java/com/project/trainingdiary/controller/ScheduleController.java
  src/main/java/com/project/trainingdiary/model/ScheduleResponseDetail.java
  src/main/java/com/project/trainingdiary/repository/ptContract/PtContractRepository.java
  src/main/java/com/project/trainingdiary/repository/schedule/ScheduleRepositoryCustom.java
  src/main/java/com/project/trainingdiary/repository/schedule/ScheduleRepositoryImpl.java
  src/main/java/com/project/trainingdiary/service/ScheduleService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTraineeService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTrainerService.java
  src/test/java/com/project/trainingdiary/service/ScheduleOpenCloseServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTraineeServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTrainerServiceTest.java
Labels: feature

#66 일정 예약 부분 수정
  src/main/java/com/project/trainingdiary/controller/PtContractController.java
  src/main/java/com/project/trainingdiary/controller/ScheduleController.java
  src/main/java/com/project/trainingdiary/dto/request/AcceptScheduleRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/ApplyScheduleRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/CancelScheduleByTraineeRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/CancelScheduleByTrainerRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/CloseScheduleRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/RegisterScheduleRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/RejectScheduleRequestDto.java
  src/main/java/com/project/trainingdiary/exception/impl/PtContractNotEnoughSession.java
  src/main/java/com/project/trainingdiary/exception/impl/ScheduleAlreadyExistException.java
  src/main/java/com/project/trainingdiary/exception/impl/ScheduleNotFoundException.java
  src/main/java/com/project/trainingdiary/exception/impl/ScheduleRangeTooLong.java
  src/main/java/com/project/trainingdiary/exception/impl/ScheduleStartIsPast.java
  src/main/java/com/project/trainingdiary/exception/impl/ScheduleStartTooSoon.java
  src/main/java/com/project/trainingdiary/exception/impl/ScheduleStartWithin1Day.java
  src/main/java/com/project/trainingdiary/exception/impl/ScheduleStatusNotOpenException.java
  src/main/java/com/project/trainingdiary/exception/impl/ScheduleStatusNotReserveApplied.java
  src/main/java/com/project/trainingdiary/exception/impl/ScheduleStatusNotReserveAppliedOrReserved.java
  src/main/java/com/project/trainingdiary/exception/impl/UsedSessionExceededTotalSession.java
  src/main/java/com/project/trainingdiary/model/ScheduleDateTimes.java
  src/main/java/com/project/trainingdiary/service/ScheduleOpenCloseService.java
  src/test/java/com/project/trainingdiary/service/ScheduleOpenCloseServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTraineeServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTrainerServiceTest.java
  src/test/java/com/project/trainingdiary/service/TrainerServiceTest.java
Labels: feature

#71 운동 일지 이미지 업로드 수정
  src/main/java/com/project/trainingdiary/exception/impl/FileNoNameException.java
  src/main/java/com/project/trainingdiary/service/WorkoutSessionService.java
  src/main/java/com/project/trainingdiary/util/ImageUploadUtil.java
  src/test/java/com/project/trainingdiary/service/WorkoutSessionServiceTest.java
Labels: bug, refactoring

#72 트레이니 정보 수정 시 남은 세션 횟수 수정
  src/main/java/com/project/trainingdiary/controller/TrainerController.java
  src/main/java/com/project/trainingdiary/dto/request/EditTraineeInfoRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/EditTraineeInfoResponseDto.java
  src/main/java/com/project/trainingdiary/dto/response/PtContractResponseDto.java
  src/main/java/com/project/trainingdiary/dto/response/RegisterScheduleResponseDto.java
  src/main/java/com/project/trainingdiary/dto/response/TraineeInfoResponseDto.java
  src/main/java/com/project/trainingdiary/entity/PtContractEntity.java
  src/main/java/com/project/trainingdiary/service/ScheduleOpenCloseService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTraineeService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTrainerService.java
  src/main/java/com/project/trainingdiary/service/TrainerService.java
  src/test/java/com/project/trainingdiary/service/ScheduleOpenCloseServiceTest.java
  src/test/java/com/project/trainingdiary/service/TrainerServiceTest.java
Labels: feature

#74 트레이니 식단 추가 (이미지 및 텍스트 추가)
  src/main/java/com/project/trainingdiary/controller/DietController.java
  src/main/java/com/project/trainingdiary/dto/request/CreateDietRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/SignUpRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/DietImageResponseDto.java
  src/main/java/com/project/trainingdiary/entity/DietEntity.java
  src/main/java/com/project/trainingdiary/repository/DietRepository.java
  src/main/java/com/project/trainingdiary/service/DietService.java
  src/main/java/com/project/trainingdiary/util/ImageUtil.java
  src/test/java/com/project/trainingdiary/service/DietServiceTest.java
Labels: feature

#76 트레이니가 신청 시 세션 횟수를 차감하도록 수정
  src/main/java/com/project/trainingdiary/controller/ScheduleController.java
  src/main/java/com/project/trainingdiary/dto/response/ApplyScheduleResponseDto.java
  src/main/java/com/project/trainingdiary/service/ScheduleTraineeService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTrainerService.java
  src/test/java/com/project/trainingdiary/service/ScheduleTraineeServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTrainerServiceTest.java
Labels: bug

#77 운동 일지 삭제
  src/main/java/com/project/trainingdiary/controller/WorkoutSessionController.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutSessionUpdateRequestDto.java
  src/main/java/com/project/trainingdiary/entity/BaseEntity.java
  src/main/java/com/project/trainingdiary/entity/WorkoutSessionEntity.java
  src/main/java/com/project/trainingdiary/service/WorkoutSessionService.java
  src/test/java/com/project/trainingdiary/service/WorkoutSessionServiceTest.java
Labels: feature

#85 이메일 인증 디자인 개선, 제목 및 유효시간까지 포함
  src/main/java/com/project/trainingdiary/provider/EmailProvider.java
  src/main/java/com/project/trainingdiary/service/UserService.java
  src/main/java/com/project/trainingdiary/util/VerificationCodeGeneratorUtil.java
Labels: enhancement

#83 식단 목록 조회 기능 (트레이너, 트레이니 둘 다 가능) API 구현
  src/main/java/com/project/trainingdiary/controller/DietController.java
  src/main/java/com/project/trainingdiary/controller/TrainerController.java
  src/main/java/com/project/trainingdiary/controller/UserController.java
  src/main/java/com/project/trainingdiary/dto/request/CreateDietRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/DietImageResponseDto.java
  src/main/java/com/project/trainingdiary/repository/DietRepository.java
  src/main/java/com/project/trainingdiary/service/DietService.java
  src/test/java/com/project/trainingdiary/service/DietServiceTest.java
Labels: feature

#86 식단 상세 조회 API 구현
  src/main/java/com/project/trainingdiary/controller/DietController.java
  src/main/java/com/project/trainingdiary/dto/response/DietDetailsInfoResponseDto.java
  src/main/java/com/project/trainingdiary/exception/impl/DietNotExistException.java
  src/main/java/com/project/trainingdiary/provider/EmailProvider.java
  src/main/java/com/project/trainingdiary/repository/DietRepository.java
  src/main/java/com/project/trainingdiary/security/JwtAuthenticationFilter.java
  src/main/java/com/project/trainingdiary/service/DietService.java
  src/main/java/com/project/trainingdiary/service/UserService.java
  src/test/java/com/project/trainingdiary/service/DietServiceTest.java
  src/test/java/com/project/trainingdiary/service/UserServiceTest.java
Labels: feature

#89 swagger 작업
  src/main/java/com/project/trainingdiary/controller/WorkoutSessionController.java
  src/main/java/com/project/trainingdiary/controller/WorkoutTypeController.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutCreateRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutImageRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutSessionCreateRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutSessionUpdateRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutTypeCreateRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutTypeUpdateRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutUpdateRequestDto.java
  src/main/java/com/project/trainingdiary/dto/request/WorkoutVideoRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/WorkoutResponseDto.java
  src/main/java/com/project/trainingdiary/entity/WorkoutEntity.java
  src/main/java/com/project/trainingdiary/exception/impl/InvalidUserRoleTypeException.java
  src/main/java/com/project/trainingdiary/exception/impl/WorkoutSessionAccessDeniedException.java
  src/test/java/com/project/trainingdiary/service/WorkoutSessionServiceTest.java
Labels: documentation

#88 트레이니의 식단 삭제 API 구현
  src/main/java/com/project/trainingdiary/controller/DietController.java
  src/main/java/com/project/trainingdiary/service/DietService.java
  src/main/java/com/project/trainingdiary/util/ImageUtil.java
  src/test/java/com/project/trainingdiary/service/DietServiceTest.java
Labels: feature

#91 일정 예약 신청 시 트레이너에게 푸시 알림 보냄
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  scripts/startup.sh
  src/main/java/com/project/trainingdiary/component/FcmPushNotification.java
  src/main/java/com/project/trainingdiary/config/FirebaseConfig.java
  src/main/java/com/project/trainingdiary/controller/NotificationController.java
  src/main/java/com/project/trainingdiary/dto/request/RegisterFcmTokenRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/NotificationResponseDto.java
  src/main/java/com/project/trainingdiary/entity/FcmTokenEntity.java
  src/main/java/com/project/trainingdiary/entity/NotificationEntity.java
  src/main/java/com/project/trainingdiary/entity/TraineeEntity.java
  src/main/java/com/project/trainingdiary/entity/TrainerEntity.java
  src/main/java/com/project/trainingdiary/model/NotificationType.java
  src/main/java/com/project/trainingdiary/repository/FcmTokenRepository.java
  src/main/java/com/project/trainingdiary/repository/NotificationRepository.java
  src/main/java/com/project/trainingdiary/service/FcmTokenService.java
  src/main/java/com/project/trainingdiary/service/NotificationService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTraineeService.java
  src/main/java/com/project/trainingdiary/util/NotificationMessageMaker.java
  src/test/java/com/project/trainingdiary/service/FcmTokenServiceTest.java
  src/test/java/com/project/trainingdiary/service/NotificationServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTraineeServiceTest.java
Labels: feature

#94 사용되지 않는 코드 제거
  src/main/java/com/project/trainingdiary/controller/SampleController.java
  src/main/java/com/project/trainingdiary/dto/request/ExampleRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/CommonResponse.java
  src/main/java/com/project/trainingdiary/dto/response/CustomResponse.java
Labels: refactoring

#95 읽지 않은 메시지 표시 필드 관리
  src/main/java/com/project/trainingdiary/dto/response/MemberInfoResponseDto.java
  src/main/java/com/project/trainingdiary/entity/TraineeEntity.java
  src/main/java/com/project/trainingdiary/entity/TrainerEntity.java
  src/main/java/com/project/trainingdiary/service/NotificationService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTraineeService.java
  src/main/java/com/project/trainingdiary/service/UserService.java
  src/test/java/com/project/trainingdiary/service/NotificationServiceTest.java
Labels: feature

#107 트레이너 식단에 댓글 추가 기능 구현
  src/main/java/com/project/trainingdiary/controller/CommentController.java
  src/main/java/com/project/trainingdiary/dto/request/comment/AddCommentRequestDto.java
  src/main/java/com/project/trainingdiary/dto/response/comment/CommentDto.java
  src/main/java/com/project/trainingdiary/dto/response/diet/DietDetailsInfoResponseDto.java
  src/main/java/com/project/trainingdiary/entity/CommentEntity.java
  src/main/java/com/project/trainingdiary/entity/DietEntity.java
  src/main/java/com/project/trainingdiary/exception/comment/TrainerCommentNotExistException.java
  src/main/java/com/project/trainingdiary/repository/CommentRepository.java
  src/main/java/com/project/trainingdiary/repository/TrainerCommentRepository.java
  src/main/java/com/project/trainingdiary/service/CommentService.java
  src/main/java/com/project/trainingdiary/service/DietService.java
  src/main/java/com/project/trainingdiary/service/TrainerCommentService.java
  src/test/java/com/project/trainingdiary/service/CommentServiceTest.java
  src/test/java/com/project/trainingdiary/service/DietServiceTest.java
Labels: feature

#114 Swagger 문서 API 수정
  src/main/java/com/project/trainingdiary/config/SwaggerConfig.java
Labels: documentation

#112 Jackson 모듈 및 타임존 설정 추가
  src/main/java/com/project/trainingdiary/config/AppConfig.java
  src/main/java/com/project/trainingdiary/util/VerificationCodeGeneratorUtil.java
Labels: enhancement

#118 코드 변화가 아닌 문서 변경 푸시에서 github action이 수행되지 않도록 함
  .github/workflows/deploy.yml
Labels: enhancement

#117 일정 상태 응답의 필드 이름을 scheduleStatus로 통일
  src/main/java/com/project/trainingdiary/dto/response/schedule/ApplyScheduleResponseDto.java
  src/main/java/com/project/trainingdiary/dto/response/schedule/CancelScheduleByTraineeResponseDto.java
  src/main/java/com/project/trainingdiary/dto/response/schedule/CancelScheduleByTrainerResponseDto.java
  src/main/java/com/project/trainingdiary/dto/response/schedule/RejectScheduleResponseDto.java
  src/main/java/com/project/trainingdiary/model/ScheduleResponseDetail.java
  src/main/java/com/project/trainingdiary/repository/schedule/ScheduleRepositoryImpl.java
  src/test/java/com/project/trainingdiary/service/ScheduleOpenCloseServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTraineeServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTrainerServiceTest.java
Labels: enhancement

#122 트레이너 댓글 삭제 기능 구현 API
  src/main/java/com/project/trainingdiary/controller/CommentController.java
  src/main/java/com/project/trainingdiary/dto/response/comment/CommentDto.java
  src/main/java/com/project/trainingdiary/dto/response/diet/DietDetailsInfoResponseDto.java
  src/main/java/com/project/trainingdiary/entity/BaseEntity.java
  src/main/java/com/project/trainingdiary/repository/DietRepository.java
  src/main/java/com/project/trainingdiary/service/CommentService.java
  src/main/java/com/project/trainingdiary/service/DietService.java
  src/test/java/com/project/trainingdiary/service/CommentServiceTest.java
  src/test/java/com/project/trainingdiary/service/DietServiceTest.java
Labels: feature

#126 쿠키 처리 로직 개선, 환경에 따라 쿠키가 전달되록 버그 해결
  src/main/java/com/project/trainingdiary/controller/UserController.java
  src/main/java/com/project/trainingdiary/provider/CookieProvider.java
  src/main/java/com/project/trainingdiary/security/JwtAuthenticationFilter.java
  src/main/java/com/project/trainingdiary/security/SecurityConfig.java
  src/main/java/com/project/trainingdiary/service/UserService.java
Labels: bug

#124 운동 일지 미디어 관련 수정 및 기능 추가
  build.gradle
  src/main/java/com/project/trainingdiary/component/OctetStreamReadMsgConverter.java
  src/main/java/com/project/trainingdiary/config/WebConfig.java
  src/main/java/com/project/trainingdiary/controller/WorkoutSessionController.java
  src/main/java/com/project/trainingdiary/controller/WorkoutTypeController.java
  src/main/java/com/project/trainingdiary/dto/response/workout/session/WorkoutImageResponseDto.java
  src/main/java/com/project/trainingdiary/dto/response/workout/session/WorkoutSessionListResponseDto.java
  src/main/java/com/project/trainingdiary/dto/response/workout/session/WorkoutSessionResponseDto.java
  src/main/java/com/project/trainingdiary/dto/response/workout/session/WorkoutVideoResponseDto.java
  src/main/java/com/project/trainingdiary/provider/S3ImageProvider.java
  src/main/java/com/project/trainingdiary/provider/S3VideoProvider.java
  src/main/java/com/project/trainingdiary/service/WorkoutSessionService.java
  src/main/java/com/project/trainingdiary/util/ConvertCloudFrontUrlUtil.java
  src/main/java/com/project/trainingdiary/util/ImageUploadUtil.java
  src/main/java/com/project/trainingdiary/util/MediaUtil.java
  src/main/java/com/project/trainingdiary/util/VideoUtil.java
  src/main/resources/application-sample.yml
  src/test/java/com/project/trainingdiary/service/WorkoutSessionServiceTest.java
  src/test/resources/application-test.yml
Labels: feature, refactoring

#128 여러 상황에 푸시 알림 전송
  src/main/java/com/project/trainingdiary/component/FcmPushNotification.java
  src/main/java/com/project/trainingdiary/config/ScheduleConfig.java
  src/main/java/com/project/trainingdiary/dto/response/notification/NotificationResponseDto.java
  src/main/java/com/project/trainingdiary/entity/NotificationEntity.java
  src/main/java/com/project/trainingdiary/exception/notification/UnsupportedNotificationTypeException.java
  src/main/java/com/project/trainingdiary/model/NotificationMessage.java
  src/main/java/com/project/trainingdiary/model/type/NotificationType.java
  src/main/java/com/project/trainingdiary/repository/NotificationRepository.java
  src/main/java/com/project/trainingdiary/repository/ptContract/PtContractRepository.java
  src/main/java/com/project/trainingdiary/repository/schedule/ScheduleRepository.java
  src/main/java/com/project/trainingdiary/service/NotificationService.java
  src/main/java/com/project/trainingdiary/service/PtContractService.java
  src/main/java/com/project/trainingdiary/service/ScheduleOpenCloseService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTraineeService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTrainerService.java
  src/main/java/com/project/trainingdiary/util/NotificationMessageGeneratorUtil.java
  src/test/java/com/project/trainingdiary/service/NotificationServiceTest.java
  src/test/java/com/project/trainingdiary/service/PtContractServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleOpenCloseServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTraineeServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTrainerServiceTest.java
Labels: feature

#131 클라이언트에서 받는 에러 코드를 간소화
  src/main/java/com/project/trainingdiary/controller/PtContractController.java
  src/main/java/com/project/trainingdiary/controller/ScheduleController.java
  src/main/java/com/project/trainingdiary/exception/ptcontract/PtContractNotEnoughSessionException.java
  src/main/java/com/project/trainingdiary/exception/schedule/ScheduleAlreadyExistException.java
  src/main/java/com/project/trainingdiary/exception/schedule/ScheduleRangeTooLongException.java
  src/main/java/com/project/trainingdiary/exception/schedule/ScheduleStartIsPastException.java
  src/main/java/com/project/trainingdiary/exception/schedule/ScheduleStartTooSoonException.java
  src/main/java/com/project/trainingdiary/exception/schedule/ScheduleStartWithin1DayException.java
  src/main/java/com/project/trainingdiary/exception/schedule/ScheduleStatusNotOpenException.java
  src/main/java/com/project/trainingdiary/exception/schedule/ScheduleStatusNotReserveAppliedException.java
  src/main/java/com/project/trainingdiary/exception/schedule/ScheduleStatusNotReserveAppliedOrReservedException.java
  src/main/java/com/project/trainingdiary/service/ScheduleTraineeService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTrainerService.java
  src/test/java/com/project/trainingdiary/service/ScheduleTraineeServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTrainerServiceTest.java
Labels: bug

#134 이메일 전송 비동기 처리 및 오류 코드 변경
  src/main/java/com/project/trainingdiary/TrainingDiaryApplication.java
  src/main/java/com/project/trainingdiary/controller/UserController.java
  src/main/java/com/project/trainingdiary/exception/user/AuthenticationUserNotFoundException.java
  src/main/java/com/project/trainingdiary/exception/user/WrongPasswordException.java
  src/main/java/com/project/trainingdiary/provider/EmailProvider.java
  src/main/java/com/project/trainingdiary/service/UserService.java
  src/test/java/com/project/trainingdiary/service/UserServiceTest.java
Labels: enhancement

#138 PT 계약 생성 시 없는 이메일을 등록할 경우 에러코드로 406이 나가도록 수정
  src/main/java/com/project/trainingdiary/controller/PtContractController.java
  src/main/java/com/project/trainingdiary/exception/ptcontract/PtContractTrainerEmailNotExistException.java
  src/main/java/com/project/trainingdiary/service/PtContractService.java
  src/test/java/com/project/trainingdiary/service/PtContractServiceTest.java
Labels: bug

#139 푸시 알림 문구에 트레이니에게도 님을 붙임
  src/main/java/com/project/trainingdiary/util/NotificationMessageGeneratorUtil.java
Labels: bug

#140 PT 계약에서 직접 날짜 시간 포맷팅을 하지 않고, 전역 옵션을 사용
  src/main/java/com/project/trainingdiary/dto/response/ptcontract/PtContractResponseDto.java
  src/main/java/com/project/trainingdiary/entity/PtContractEntity.java
  src/main/java/com/project/trainingdiary/service/ScheduleTraineeService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTrainerService.java
  src/test/java/com/project/trainingdiary/service/ScheduleTraineeServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleTrainerServiceTest.java
Labels: enhancement

#146 PT 계약 생성과 일정 등록 시에 트레이니에게 알림을 보냄
  src/main/java/com/project/trainingdiary/service/PtContractService.java
  src/main/java/com/project/trainingdiary/service/ScheduleOpenCloseService.java
  src/test/java/com/project/trainingdiary/service/PtContractServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleOpenCloseServiceTest.java
Labels: bug

#148 트레이너 API 리팩토링
  src/main/java/com/project/trainingdiary/controller/TrainerController.java
  src/main/java/com/project/trainingdiary/dto/response/trainer/TraineeInfoResponseDto.java
  src/main/java/com/project/trainingdiary/service/TraineeService.java
  src/main/java/com/project/trainingdiary/service/TrainerService.java
  src/main/java/com/project/trainingdiary/service/UserService.java
Labels: refactoring

#149 트레이너와 트레이니 샘플 데이터 추가 스크립트
  scripts/insert_trainers_and_trainees.sql
  scripts/insert_users.sh
Labels: enhancement

#155 일정 열기 및 일정 등록 시 기존 일정을 가져올 때, 해당 트레이너의 일정만 가져오도록 함
  src/main/java/com/project/trainingdiary/repository/schedule/ScheduleRepository.java
  src/main/java/com/project/trainingdiary/service/ScheduleOpenCloseService.java
  src/test/java/com/project/trainingdiary/service/ScheduleOpenCloseServiceTest.java
Labels: bug

#157 [Refactoring] 동영상 업로드 속도 개선
  src/main/java/com/project/trainingdiary/controller/WorkoutSessionController.java
  src/main/java/com/project/trainingdiary/exception/workout/MediaCountExceededException.java
  src/main/java/com/project/trainingdiary/provider/S3ImageProvider.java
  src/main/java/com/project/trainingdiary/util/MediaUtil.java
  src/main/java/com/project/trainingdiary/util/VideoUtil.java
Labels: refactoring

#158 트레이니가 기존 유효한 PT 계약이 있다면, 새로운 PT 계약을 맺으려 할 때 에러를 냄
  src/main/java/com/project/trainingdiary/controller/PtContractController.java
  src/main/java/com/project/trainingdiary/exception/ptcontract/PtContractTraineeCanHaveOnlyOneException.java
  src/main/java/com/project/trainingdiary/repository/ptContract/PtContractRepository.java
  src/main/java/com/project/trainingdiary/service/PtContractService.java
  src/test/java/com/project/trainingdiary/service/PtContractServiceTest.java
Labels: bug

#160 PT 계약 종료 시 미래에 남아있던 예약 일정을 모두 제거
  src/main/java/com/project/trainingdiary/controller/PtContractController.java
  src/main/java/com/project/trainingdiary/repository/schedule/ScheduleRepository.java
  src/main/java/com/project/trainingdiary/repository/schedule/ScheduleRepositoryCustom.java
  src/main/java/com/project/trainingdiary/repository/schedule/ScheduleRepositoryImpl.java
  src/main/java/com/project/trainingdiary/service/PtContractService.java
  src/main/java/com/project/trainingdiary/service/ScheduleTraineeService.java
  src/test/java/com/project/trainingdiary/service/PtContractServiceTest.java
Labels: bug

#150 ImageUtil 클래스를 S3 역할 따로 구분 및 식단 서비스 컨트롤러 리팩토링
  src/main/java/com/project/trainingdiary/controller/DietController.java
  src/main/java/com/project/trainingdiary/dto/response/diet/DietDetailsInfoResponseDto.java
  src/main/java/com/project/trainingdiary/dto/response/trainer/TraineeInfoResponseDto.java
  src/main/java/com/project/trainingdiary/exception/ptcontract/PtContractNotExistException.java
  src/main/java/com/project/trainingdiary/provider/S3DietImageProvider.java
  src/main/java/com/project/trainingdiary/provider/S3Provider.java
  src/main/java/com/project/trainingdiary/service/DietService.java
  src/main/java/com/project/trainingdiary/util/ImageUtil.java
  src/main/java/com/project/trainingdiary/util/MediaUtil.java
  src/test/java/com/project/trainingdiary/service/DietServiceTest.java
  src/test/java/com/project/trainingdiary/service/ScheduleOpenCloseServiceTest.java
Labels: feature, refactoring

#162 트레이너의 트레이니 조회 API 트레이니 본인도 조회할 수 있도록 구현
  src/main/java/com/project/trainingdiary/controller/TrainerController.java
  src/main/java/com/project/trainingdiary/exception/user/UnauthorizedTraineeException.java
  src/main/java/com/project/trainingdiary/repository/ptContract/PtContractRepository.java
  src/main/java/com/project/trainingdiary/service/TrainerService.java
  src/test/java/com/project/trainingdiary/service/TrainerServiceTest.java
Labels: enhancement, feature

#164 fix: 트레이니 계약 없이 호출 가능하도록 수정
  src/main/java/com/project/trainingdiary/repository/TraineeRepository.java
  src/main/java/com/project/trainingdiary/service/TrainerService.java
Labels: bug

#167 ERD 다이어그램 추가
  README.md
  docs/images/training-diary-erd.png
Labels: documentation

#169 운동 일지를 생성할 때 회차 별 작성 문제
  src/main/java/com/project/trainingdiary/repository/WorkoutSessionRepository.java
  src/main/java/com/project/trainingdiary/service/WorkoutSessionService.java
  src/test/java/com/project/trainingdiary/service/WorkoutSessionServiceTest.java
Labels: bug

#172 다이어트 API 및 댓글 API 개선
  src/main/java/com/project/trainingdiary/controller/CommentController.java
  src/main/java/com/project/trainingdiary/controller/DietController.java
  src/main/java/com/project/trainingdiary/dto/response/diet/DietDetailsInfoResponseDto.java
  src/main/java/com/project/trainingdiary/exception/ptcontract/PtContractNotExistException.java
  src/main/java/com/project/trainingdiary/repository/DietRepository.java
  src/main/java/com/project/trainingdiary/service/DietService.java
  src/test/java/com/project/trainingdiary/service/DietServiceTest.java
Labels: enhancement

#170 트레이니의 일정 조회 시 연결된 트레이너의 다른 트레이니와의 일정을 보여주지 않음
  src/main/java/com/project/trainingdiary/repository/schedule/ScheduleRepositoryImpl.java
Labels: bug

#178 동영상 업로드 수정
  src/main/java/com/project/trainingdiary/provider/S3VideoProvider.java
  src/main/java/com/project/trainingdiary/service/WorkoutSessionService.java
  src/main/java/com/project/trainingdiary/util/VideoUtil.java
  src/main/resources/application-sample.yml
  src/test/java/com/project/trainingdiary/service/WorkoutSessionServiceTest.java
Labels: bug
